version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "image-rekognition"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1inlv8j5drwkb"
s3_prefix = "image-rekognition"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
